spring.application.name=TravelApp

# --- RENDER INTERNAL POSTGRESQL CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://dpg-d902945aeets73dl2uh0-a:5432/travel_db_v3be
spring.datasource.username=travel_db_v3be_user
spring.datasource.password=1OAshxhi9PHKt8ri7OdBz0me5NJWUnVJ
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE CONFIGURATION ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- THYMELEAF & SERVER CONFIGURATION ---
spring.thymeleaf.cache=false
server.port=8080

# --- GEMINI AI CHATBOT SYSTEM CONFIGURATION ---
gemini.api.key=AQ.Ab8RN6KyZSh3tDkVzb-ml0Y4zomiHJea0OovMxQMlvo8tdQivg

# --- DEFAULT ADMIN CONFIGURATION ---
travelapp.default-admin.email=admin@example.com
travelapp.default-admin.password=admin123

# --- MAIL SERVER CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=travel.genie51@gmail.com
spring.mail.password=yaxxvjdfxzeidgge 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
