spring.application.name=TravelApp

spring.datasource.url=jdbc:postgresql://dpg-d902945aeets73dl2uh0-a:5432/travel_db_v3be
spring.datasource.username=travel_db_v3be_user
spring.datasource.password=ඔයාගේ_DATABASE_PASSWORD_එක_මෙතනට_දාන්න
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.port=8080

travelapp.default-admin.email=admin@example.com
travelapp.default-admin.password=admin123

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=travel.genie51@gmail.com
spring.mail.password=yaxxvjdfxzeidgge 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
