spring.application.name=TravelApp

# --- RENDER INTERNAL POSTGRESQL CONFIGURATION ---
# Hostname, Port සහ Database Name ඔක්කොම එකතු කරලා නිවැරදිම Format එකෙන් හදලා තියෙන්නේ:
spring.datasource.url=jdbc:postgresql://dpg-d902945aeets73dl2uh0-a:5432/travel_db_v3be
spring.datasource.username=travel_db_v3be_user
# ⚠️ මතක ඇතුව ඔයාගේ Render Connections පිටුවේ පල්ලෙහාම තියෙන Password එක මෙන්න මෙතනට Paste කරන්න:
spring.datasource.password=1OAshxhi9PHKt8ri7OdBz0me5NJWUnVJ
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE CONFIGURATION ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.port=8080

# --- DEFAULT ADMIN CONFIGURATION ---
travelapp.default-admin.email=admin@example.com
travelapp.default-admin.password=admin123

# --- MAIL SERVER CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=travel.genie51@gmail.com
spring.mail.password=yaxxvjdfxzeidgge 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true